name: bcard_scanner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  google_mlkit_text_recognition: ^0.13.0
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.19.0
  uuid: ^4.2.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.1
  cupertino_icons: ^1.0.6
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  qr_flutter: ^4.1.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  archive: ^4.0.7
  file_picker: ^10.3.8
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#4E54C8"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
